#Hibernate
spring:
  jpa:
    show-sql: false
  hibernate:
    ddl-auto: update

#Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/topdb
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#Thymeleaf
  thymeleaf:
    cache: false

#Spring dev tools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true