#Hibernate
spring:
#  jpa:
#    show-sql: false
#  hibernate:
#    ddl-auto: update

##Datasource
#  datasource:
#    url: jdbc:mysql://localhost:3306/topdb
#    username: root
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

# Derby datasource
  datasource:
    url: jdbc:derby:topDB;create=true;
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    username: topdb
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 50000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 5

# Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.DerbyDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.DerbyDialect

#Thymeleaf
  thymeleaf:
    cache: false

#Spring dev tools
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true